### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by dgilperez** [whatcould/webshims-rails#17]
It seems that ``webshims/extras/modernizr-custom.js`` was removed somewhere between 1.14.3 and 1.14.6. If that's OK, I suggest you update the README to remove the line to add to ``application.js``

````
    //= require webshims/extras/modernizr-custom
````

**Comment by whatcould** [comment]
Thanks to both of you for reminding me — I hit this snag myself the last time I upgraded, but forgot to come back and fix the docs.

**Comment by dgilperez** [comment]
Great!
