### ISSUE TITLE
rake asset:precompile failing (sass:Syntax error)

### ISSUE THREAD

**Issue by drewB** [whatcould/webshims-rails#23]
When I do a rake asset:precompile (ruby 1.9.3), I get the following error:

    Sass::SyntaxError: Invalid CSS after "": expected selector or at-rule, was "%iconbase {"

Stack trace points to 'javascripts/webshims/shims/jme/_icons.scss'  

I originally had the issue described in https://github.com/whatcould/webshims-rails/issues/11, but after updating uglifier, now I get this error.

**Comment by whatcould** [comment]
I tried to recreate this issue but could not make an application run on 1.9.3 (seems like not that long ago that 1.9 was the hotness!). 

I think you should just be able to skip precompiling by following the directions (#1) for Rails 4.

**Comment by drewB** [comment]
ok thanks.  I just ended up including webshims through cdnjs.
