### ISSUE TITLE
Should depend on jquery-rails

### ISSUE THREAD

**Issue by singpolyma** [whatcould/webshims-rails#25]
since it is required to work

**Comment by whatcould** [comment]
jQuery is required, but not jquery-rails — you only really need jquery-rails if you're using UJS, which a lot of devs don't use.

**Comment by singpolyma** [comment]
How else would you suggest to put in jquery so this gem will work?

**Comment by whatcould** [comment]
* You could just drop the jquery library in vendor/assets/javascripts/jquery.js, like everybody used to do.
* You could just add a script tag that points a hosted (CDN) jquery URL.
* I like using the jquery-rails-cdn gem, which references jQuery on a CDN on production but will fallback to a local version, like when you're on a laptop without an internet connection.
