### ISSUE TITLE
Webshims::Rails::WEBSHIMS_VERSION in asset doesn't cause file to be reloaded when version changes

### ISSUE THREAD

**Issue by jeremywadsack** [whatcould/webshims-rails#28]
I'm running into more cache-busting problems in development and test (Capybara-Webkit driver). When I updated webshims from 1.15.10 to 1.16.0, the browser and webkit driver continued to load the old version of the assets that includes the line to set the path:

```
$.webshims.setOptions "basePath", "/webshims/<%= Webshims::Rails::WEBSHIMS_VERSION %>/shims/"
```

When I added a comment above that line, then everything started loading the new version.

I can't find the details in Sprockets source, but I wonder if the fingerprint digest is based on the file content _on-disk_ rather than the content after ERB has been applied.

**Comment by whatcould** [comment]
My environment did the same thing — I was able to fix it by clearing tmp and restarting the server. I was surprised to find that I had the same issue in production after a precompile — I guess there is some caching going on when Sprockets precompiles the ERB file.

Not sure if there's a way around it, might have to remove the suggestion to use ERB to set the asset path based on the WEBSHIMS_VERSION constant...  there's maybe a workaround suggested here (https://github.com/sstephenson/sprockets/issues/563) with `depend_on` but that seems like more of a kudge than just changing the version every time.
